In [1]:
import tensorflow as tf

In [2]:
data=tf.keras.datasets.mnist

In [3]:
(x_train,y_train),(x_test,y_test)=data.load_data()

In [9]:
x_train=x_train/255
x_test=x_test/255
#STandardizing the data

In [10]:
x_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [33]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                 tf.keras.layers.Dense(80,activation='relu'),
                                 tf.keras.layers.Dropout(0.3),
                                 tf.keras.layers.Dense(10),
                                 tf.keras.layers.Softmax()])

In [34]:
pred=model(x_train)#pred, direcly give the probability scores uncalibrated for each class for every datatype

In [35]:
pred

<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[0.09840594, 0.11645571, 0.06851263, ..., 0.1317562 , 0.09244032,
        0.0726179 ],
       [0.0822762 , 0.08895351, 0.10459178, ..., 0.10849738, 0.10848425,
        0.13269345],
       [0.07911851, 0.11424597, 0.09266979, ..., 0.06412622, 0.11303299,
        0.09817558],
       ...,
       [0.07803803, 0.11886534, 0.07279748, ..., 0.10356779, 0.08838356,
        0.07333308],
       [0.06765378, 0.0735689 , 0.09442294, ..., 0.0807404 , 0.09512077,
        0.11880218],
       [0.08375682, 0.09225215, 0.07964917, ..., 0.09426051, 0.09502866,
        0.15918918]], dtype=float32)>

In [36]:
calibrated_pred=tf.nn.softmax(pred)
calibrated_pred

<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[0.09977973, 0.10159709, 0.09684113, ..., 0.10316353, 0.09918626,
        0.0972395 ],
       [0.09818842, 0.09884625, 0.10040419, ..., 0.10079709, 0.10079577,
        0.10326573],
       [0.09788036, 0.10137974, 0.09921578, ..., 0.09642385, 0.10125685,
        0.09976355],
       ...,
       [0.09777932, 0.101854  , 0.09726824, ..., 0.10030774, 0.09879614,
        0.09732035],
       [0.09678111, 0.09735528, 0.09940685, ..., 0.09805597, 0.09947624,
        0.10186008],
       [0.09832974, 0.09916864, 0.09792665, ..., 0.099368  , 0.09944436,
        0.10603389]], dtype=float32)>

In [37]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1],calibrated_pred[:1])

<tf.Tensor: shape=(), dtype=float32, numpy=2.308499>

In [38]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
#Makes the model ready, where we set all the values

In [39]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.6085 - accuracy: 0.8756
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.5405 - accuracy: 0.9284
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.5264 - accuracy: 0.9402
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.5177 - accuracy: 0.9477
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 1.5122 - accuracy: 0.9523


In [40]:
#Check the performance of the model on test/CV
#What is Verbose: https://stackoverflow.com/questions/47902295/what-is-the-use-of-verbose-in-keras-while-validating-the-model
model.evaluate(x_test,y_test,verbose=1)

313/313 [==============================] - 1s 1ms/step - loss: 1.5003 - accuracy: 0.9634


[1.5003483295440674, 0.9634000062942505]

In [41]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [42]:
probability_model(x_train)
#This is the final probability

<tf.Tensor: shape=(60000, 10), dtype=float32, numpy=
array([[0.08543087, 0.08543087, 0.08543087, ..., 0.08543087, 0.08543087,
        0.08543087],
       [0.23196931, 0.08533674, 0.08533674, ..., 0.08533674, 0.08533674,
        0.08533674],
       [0.08533721, 0.08533721, 0.08533994, ..., 0.08533722, 0.08533721,
        0.08533737],
       ...,
       [0.08533674, 0.08533674, 0.08533674, ..., 0.08533674, 0.08533674,
        0.08533674],
       [0.08533701, 0.085337  , 0.08533759, ..., 0.085337  , 0.085337  ,
        0.085337  ],
       [0.08535255, 0.08534048, 0.08534048, ..., 0.08534069, 0.23191032,
        0.0853416 ]], dtype=float32)>

## Loading CSV file in Tensorflow

In [ ]:
#https://www.tensorflow.org/tutorials/load_data/csv

In [44]:
import pandas as pd
import numpy as np
from tensorflow.keras import layers

'download.tensorflow.org' is not recognized as an internal or external command,
operable program or batch file.


In [53]:
abalone_train = pd.read_csv("https://storage.googleapis.com/download.tensorflow.org/data/abalone_train.csv",names=["Length", "Diameter", "Height", "Whole weight", "Shucked weight","Viscera weight", "Shell weight", "Age"])

In [54]:
abalone_train

Length  Diameter  Height  Whole weight  Shucked weight  Viscera weight  \
0      0.435     0.335   0.110        0.3340          0.1355          0.0775   
1      0.585     0.450   0.125        0.8740          0.3545          0.2075   
2      0.655     0.510   0.160        1.0920          0.3960          0.2825   
3      0.545     0.425   0.125        0.7680          0.2940          0.1495   
4      0.545     0.420   0.130        0.8790          0.3740          0.1695   
...      ...       ...     ...           ...             ...             ...   
3315   0.605     0.475   0.180        0.9365          0.3940          0.2190   
3316   0.700     0.525   0.190        1.6015          0.7070          0.3650   
3317   0.530     0.420   0.130        0.8365          0.3745          0.1670   
3318   0.395     0.315   0.105        0.3515          0.1185          0.0910   
3319   0.450     0.355   0.120        0.4120          0.1145          0.0665   

      Shell weight  Age  
0           0.0965    7  
1           0.2250    6  
2           0.3700   14  
3           0.2600   16  
4           0.2300   13  
...            ...  ...  
3315        0.2950   15  
3316        0.4300   10  
3317        0.2490   11  
3318        0.1195   16  
3319        0.1600   19  

[3320 rows x 8 columns]

In [59]:
abalone_features = abalone_train.copy()
abalone_labels = abalone_features.pop('Age')
np.array(abalone_features)

array([[0.435 , 0.335 , 0.11  , ..., 0.1355, 0.0775, 0.0965],
       [0.585 , 0.45  , 0.125 , ..., 0.3545, 0.2075, 0.225 ],
       [0.655 , 0.51  , 0.16  , ..., 0.396 , 0.2825, 0.37  ],
       ...,
       [0.53  , 0.42  , 0.13  , ..., 0.3745, 0.167 , 0.249 ],
       [0.395 , 0.315 , 0.105 , ..., 0.1185, 0.091 , 0.1195],
       [0.45  , 0.355 , 0.12  , ..., 0.1145, 0.0665, 0.16  ]])