<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 37 44 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can take matrix input from user or you can directly define the matrix and give input to the function
# reference for creating input - https://stackoverflow.com/questions/12293208/how-to-create-a-list-of-lists

# you can free to change all these codes/structure
# here A and B are list of lists
def s2l(n):
    '''Converts the strings to int list
    '''
    inp=str(input(n))
    #spliting
    inp1=inp.split(',')
    lst=[]
    lst2=[]
    #Converting to int
    for x in inp1:
        y=int(x)
        lst.append(y)
    return lst

def size(inp1):
    '''Checks the input entered if it is a size
    '''
    lst2=[]
    if len(inp1)==2:
        lst2=inp1
    else:
        print("Invalid Value")
        lst2=size(s2l("Please Enter Correct Value"))
    return lst2

def matsize(inp1,z):
    '''Checks the input entered if it is a size
    '''
    if len(inp1)==z:
        lst2=inp1
    else:
        print("Invalid Value")
        lst2=matsize(s2l("Please Enter Correct Value"),z)
    return lst2

def mat():
    '''Take an matrix input
    '''
    lst=s2l('Please enter the size of the Matrix in the format Rows,Columns: ')
    lst2=size(lst)
    row=lst2[0]
    col=lst2[1]
    i=1
    fmat=[]
    while i<=row:
        inp1=s2l("Please enter the values in row {} as 12,13,14 :" .format(i))
        z=lst2[1]
        lst3=[]
        if len(inp1)==z:
            lst3=inp1
            
        else:
            print("Invalid Value")
            lst3=matsize(s2l("Please Enter Correct Value"),z)
        i+=1
        fmat.append(lst3)
    return fmat
    
def col_con(matr,c):
    '''This function returns a seperate column from matrix M2 based on the values of c
    '''
    lst1=[]
    r=len(matr)
    for x in range(r):
        lst1.append(matr[x][c])
    return lst1

def val(m1,m2,r,c):
    '''This function returns the individual values for the resultant matrix
    '''
    mid=[]
    m2col=col_con(m2,c) #where r & c is the number of rows and columns
    loop=len(m1)
    for x in range(loop):
        x2=m1[r][x] * m2col[x]
        mid.append(x2)
    m=sum(mid)
    return m

def mult(m1,m2):
    '''This function uses "col_con" to convert the m2 column to row, then find individual value for result. Returns the result
    '''
    
    if (len(m1[0]) != len(m2)):
        print("Multiplication can only be done when the 'number of column in Matrix 1' is equal to 'Number of Rows in Matrix 2'")
    else:
        lst=[]
        for n in range(0,len(m2[0])):
            res=[]
            lst.append(0)
            for y in range(0,len(m1)):
                lst3=lst.copy()
                res.append(lst3)         
        for x in range (len(m1)):
            for y in range(len(m2[0])):
                res[x][y]=val(m1,m2,x,y)
        return res

mat1=mat()
mat2=mat()

print(mult(mat1,mat2))

#Reference website used: https://learncodingfast.com/python-programming-challenge-2-multiplying-matrices-without-numpy/

Please enter the size of the Matrix in the format Rows,Columns: 3,3
Please enter the values in row 1 as 12,13,14 :1,2,3
Please enter the values in row 2 as 12,13,14 :1,2,3
Please enter the values in row 3 as 12,13,14 :1,2,3
Please enter the size of the Matrix in the format Rows,Columns: 3,4
Please enter the values in row 1 as 12,13,14 :1,2,3,4
Please enter the values in row 2 as 12,13,14 :1,2,3,4
Please enter the values in row 3 as 12,13,14 :1,2,3,4
[[6, 12, 18, 24], [6, 12, 18, 24], [6, 12, 18, 24]]


<h3> Q2: Proportional Sampling - Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

Consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
from random import uniform
import random
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

#video link for the topic - https://www.appliedaicourse.com/lecture/11/applied-machine-learning-online-course/2876/proportional-sampling/2/module-2-data-science-exploratory-data-analysis-and-data-visualization
# you can free to change all these codes/structure
val=[0,5,27,6,13,28,100,45,10,79]
def pick_a_number_from_list(val):
    '''This function performs the calculation needed to calculate the Proportional Sampling
    '''
    dat=sum(val)
    #print(dat)
    lst1=[]
    lst2=[]
    for i in val:
        raw=i/dat
        lst1.append(raw)
    x1=0
    for x in lst1:
        x2=x1+x
        lst2.append(x2)
        x1=x2
    from random import uniform
    x3=random.uniform(0,1)
    i=0
    for n in lst2:
        i=i+1
        if x3<=n:
            break;
    fin=val[i-1]
    return fin
    #print("The value selected on random is ",val[i-1])

#print(i)
#print(x3)
#print(lst1)
#print(lst2)
    # your code here for picking an element from with the probability propotional to its magnitude
    #.
    #.
    #.

def sampling_based_on_magnitued():
    for i in range(1,100):
        number = pick_a_number_from_list(val)
        print(number)

sampling_based_on_magnitued()

100
100
45
28
45
100
13
100
79
45
13
10
100
79
79
100
45
100
79
79
79
79
45
100
45
13
28
79
100
27
100
28
45
27
6
100
100
79
13
100
45
79
45
100
79
100
45
100
79
79
100
100
100
28
100
45
100
28
79
45
45
79
100
79
45
45
13
79
79
5
45
100
79
79
79
100
100
79
79
45
79
100
45
28
79
45
79
100
100
79
100
5
6
100
28
100
100
100
79


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
inp=str(input('Please Enter your details: '))
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# try to complete this question using regular expressions
# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(Strings):
    '''Function to replace digits to #
    '''
    import re
    pat=(r'[0-9]') #Declaring raw values using "r" and the value that needs to be searched [0-9]
    lst=re.findall(pat, inp) #Command to find the values pat=pattern, inp=Input value
    dat=''.join(lst) #Joining the values in the list
    fin=re.sub('\d', '#', dat)#Substituting # for any digits
    return fin
    # write your code
    # 
 # modified string which is after replacing the # with digits

answer=replace_digits(inp)
print(answer)

Please Enter your details: #2a$#b%c%561#
####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 22, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 22
student6 43
student1 45
c.
student9 22
student6 43
student1 45
student7 47
student5 48
</pre>

In [24]:
students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
marks = [45, 78, 12, 14, 48, 43, 47, 98, 22, 80]

def display_dash_board(students, marks):
    '''Function to calculate the values
    '''
    raw=dict(zip(marks, students)) #using marks as the keys
    top=sorted(raw) #Ascend
    low=sorted(raw, reverse=True) #Desc
    s_mark=sorted(marks)
    lst1=[]
    lst2=[]
    lst3=[]
    x_25=int((len(top) * 0.25))
    x_75=int((len(top) * 0.75))
    dum=[]
    for x in top:
        if (x>s_mark[x_25-1]) & (x<s_mark[x_75]): #using -1 to also consider the 2nd element.
            dum.append(x)
            num=sorted(dum)
            #print(num)
    print('The Top Scorers\n')
    for x in range(5):
        print(low[x],raw[low[x]])
    print('\nThe Low Scorers\n')
    for y in range(5):  
        print( top[y],raw[top[y]])
    print('\n25th to 75th percentile Scorers\n')
    for n in num:
        print(raw[n],n)

display_dash_board(students, marks)

The Top Scorers

98 student8
80 student10
78 student2
48 student5
47 student7

The Low Scorers

12 student3
14 student4
22 student9
43 student6
45 student1

25th to 75th percentile Scorers

student9 22
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

Consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> Your task is to find 5 closest points(based on cosine distance) in S from P
<br>Cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)

<img src='https://i.imgur.com/vyZZQGu.png' width=400>

Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>
 Hint - If you write the formula correctly you'll get the distance between points (6,-7) and (3,-4) = 0.065

In [25]:
import math as m

def cdis(R,S):
    '''This function calculates the distance based on formula
    '''
    (x,y)=R
    (p,q)=S
    up=((x*p)+(y*q))
    down=((m.sqrt((x**2)+(y**2)))*(m.sqrt((p**2)+(q**2))))
    fin=up/down
    ans=m.acos(fin)
    return ans

def closest_points_to_p(S, P):
    '''This function calculates the distance and sorts them
    '''
    lst=[]
    for x in S:
        n=cdis(x,P)
        tup=(n,x)
        lst.append(tup)
        det=dict(lst) 
    det2=sorted(det)
    for p in range(5):
        print(det[det2[p]])  
    
S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
closest_points_to_p(S,P)
    # write your code here
    #return closest_points_to_p 

(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/mSnQW5K.png' width=400>

Output:
YES
NO
NO
YES
</pre>

In [26]:
def ext(st):
    '''This function parses data from the string
    '''
    lst2=[]
    x1=st.split('x')
    #print(x1)
    x2=x1[1].split('y')
    #print(x2)
    lst2=[x1[0],x2[0], x2[1]]
    fin=tuple(map(lambda n:float(n), lst2))
    
    return fin


def find(red,blue,line):
    '''This function determines whether the line seperates the dots based on negative and positive values
    '''
    l=ext(line)
    (a1,b1,c1)=l
    blu=[]
    for n in red:
        (x1,y1)=n
        b=(a1*x1 + b1*y1 + c1)
        blu.append(b)
    #print(blu)
    re=[]
    for m in blue:
        (x2,y2)=m
        x=(a1*x2 + b1*y2 + c1)
        re.append(x)
    #print(re)
    b1=(all(x>0 for x in blu) and all(y<0 for y in re)) or (all(x<0 for x in blu) and all(y>0 for y in re))
    r1=(all(y>0 for y in re) and all(x<0 for x in blu)) or (all(x>0 for x in blu) and all(y<0 for y in re))
    if b1==True or r1==True:
        print("Yes")
    else:
        print('No')
        

    # your code
    #return #yes/no
red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]

lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]

for x in lines:
    find(red,blue,x)

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4

</pre>



In [44]:
# 22/03/2022 trial 2
def con(dat):
    '''This converts raw data to processible data
    '''
    lst2=[]
    lst=dat.split(',')
    #x=list(filter(lambda n:n.isdigit(),lst))
    #print(lst)
    return lst

def func(d,lst):
    full=lst
    res1=[]
    #print(d)
    dat=len(d)
    if d[0].isdigit(): #First number removed
        n1=d[0]
        d.remove(n1)
        f1=1
    else:
        n1=0
        f1=0
    dum=[]
    for x in range(0,len(d)):
        if d[x].isdigit():
            n2=d[x]
            d.remove(n2)
            f4=1
            break;
        else:
            dum.append(d[x])
            f2=0
            f4=0
            n2=0
    f3=len(dum)
    #print(f1,f2,f3,f4)
    #print(dum)
    for x1 in dum:
        d.remove(x1)
    #print(d)
    
    fin=f1+f2+f3+f4
    #print(fin)
    ans=(int(n1)+int(n2))/fin
   # print(str(int(ans)))
    if len(d)>0:
        d.insert(0,str(int(ans)))
        func(y,lst)
        ans=str(int(ans))
        res1=[ans]* fin
        res=[]
        #print(res1)
        res1.remove(ans)
        lst.insert(0,res1)
    else:
        ans=str(int(ans))
        res=[ans]* fin
        #lst.append(res)
        lst.insert(0, res)
        
    return full

no=[]
y=con("_,_,30,_,_,_,50,_,_")
x=func(y,no)
#print(x)
fin=[]
for n in x:
    fin.extend(n)
print(fin)

['10', '10', '12', '12', '12', '12', '4', '4', '4']


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [32]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings. Do not write 15 print statements.
# you can use nested loops or dictionaries to write your code


# you can free to change all these codes/structure
def compute_conditional_probabilites(A):
    '''This function computes probabilities
    '''
    lst1=[]
    lst2=[]
    for x in A:
        lst1.append(x[0]) #F's
        lst2.append(x[1]) #S's
    #print(lst1,lst2)
    raw1=sorted(list(set(lst1)))
    raw2=sorted(list(set(lst2)))
    #print(raw1, raw2)
    mast=[]
    for n3 in raw1:
        for n4 in raw2:
            b= A.count([n3,n4])
            c= lst2.count(n4)
            print(r"P[F={}|S=={}]={}/{}" .format(n3, n4,b,c))
A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]

compute_conditional_probabilites(A)

P[F=F1|S==S1]=1/4
P[F=F1|S==S2]=1/3
P[F=F1|S==S3]=0/3
P[F=F2|S==S1]=1/4
P[F=F2|S==S2]=1/3
P[F=F2|S==S3]=1/3
P[F=F3|S==S1]=0/4
P[F=F3|S==S2]=1/3
P[F=F3|S==S3]=1/3
P[F=F4|S==S1]=1/4
P[F=F4|S==S2]=0/3
P[F=F4|S==S3]=1/3
P[F=F5|S==S1]=1/4
P[F=F5|S==S2]=0/3
P[F=F5|S==S3]=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [5]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features():
    '''Function calculates the number of common words,words present and not present in both strings
    '''
    com=[]
    s1=[]
    s2=[]
    str1=str(input('Enter the first String!  ')).split()
    str2= str(input('Enter the Second String!  ')).split()
    if len(str1)>len(str2):
        bas=str2
        comp=str1
    else:
        bas=str1
        comp=str2
    for x in bas:
        if x in comp:
            com.append(x)
    for i in str1:
        if i not in str2:
            s1.append(i)
    for m in str2:
        if m not in str1:
            s2.append(m)
    
    print(len(com))
    print(s1)
    print(s2)
    # your code
    #return a, b, c

#S1= "the first column F will contain only 5 uniques values"
#S2= "the second column S will contain only 3 uniques values"
string_features()

Enter the first String!  the first column F will contain only 5 uniques values
Enter the Second String!  the second column S will contain only 3 uniques values
7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [6]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structu
def f1(x):
    '''Function which calculates the formulae for individual value
    '''
    import math
    y,ys=x
    ans=((y*math.log(ys,10))+(1-y)*(math.log(1-ys,10)))
    return ans


def compute_log_loss(y):
    '''function to calculate for all values
    '''
    x=0
    for n in y:
        x+=f1(n)
    fin=(-1)*(1/(len(y)))*x
    return fin
    # your code
    
    return loss

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)


0.42430993457031635
